### ISSUE TITLE
Mouse does not work properly under Windows 3.1

### ISSUE THREAD

**Issue by OldMadMan** [captainys/TOWNSEMU#80]
Hello,

I have been consistently using Tsugaru compiled from the latest code.

I found that the mouse does not work properly under Windows 3.0/3.1. If the mouse is set to be connected to Game Port 1, the mouse cursor will not be able to move, only the double-click action will take effect; if the mouse is set to be connected to Game Port 0, then after entering the system, the cursor will move uncontrollably to the lower right corner, and finally disappear.

**Comment by captainys** [comment]
Mouse integration works for Windows 3.1 L11 and L12.  Mouse integration is not supported on Windows 3.0 and Windows 3.1 L10.  For those environments, please use gamepad as mouse or keyboard as mouse option for the time being.

**Comment by qazmko1029** [comment]
Actually how to use keyboard as mouse to control the cursor? The help text wrote this, but use -GAMEPORT1 KEY won't let me use keyboard z,x,a,s to control the cursor, need some explanation.

-GAMEPORT1 KEY|PHYSx|ANAx|NONE
  Specify game-port emulation.  By keyboard (Arrow,Z,X,A,S), or physical gamepad.
  PHYS0,PHYS1,PHYS2,PHYS3 use physical game pad direction button (or hat switch) as up/down/left/right.
  PHYS0CAPCOM,PHYS1CAPCOM,PHYS2CAPCOM,PHYS3CAPCOM use physcal game pad as CAPCOM CPSF Joystick.
  ANA0,ANA1,ANA2,ANA3 use physical game pad analog stick as up/down/left/right.
  KEYMOUSE use arrow keys and ZX keys for mouse cursor and buttons.
  NUMPADMOUSE use NUMPAD number keys and /* keys for mouse cursor and buttons.
  PHYS0MOUSE,PHYS1MOUSE,PHYS2MOUSE,PHYS3MOUSE use physical game pad digital axis for mouse.
  ANA0MOUSE,ANA1MOUSE,ANA2MOUSE,ANA3MOUSE use physical game pad analog axis for mouse.

**Comment by captainys** [comment]
OK.  Great!

**Comment by captainys** [comment]
I've just pushed a new source and a utility TGMOUSE.EXE.  You first need to use keybouard as mouse or gamepad as mouse to copy this TGMOUSE.EXE to your Windows 3.1 installation and register it in the Start Up program group.  Once it is running, it continuously reports Windows 3.1's mouse position to Tsugaru host.  It allows Tsugaru to calculate difference between host mouse position and Windows 3.1's mouse position and integrate mouse.  It makes MYST Japanese version playable on Tsugaru.  Probably it solves mouse-integration issue in Windows 3.1 L10 and hopefully Windows 3.0.  TGMOUSE.EXE is included in the disk image under util sub-directory.

**Comment by qazmko1029** [comment]
Tried it and it doesn't work with my l10 installation. I added it to WIN.INI or startup group and it did start, but the cursor still doesn't move as the host cursor. command: -GAMEPORT0 MOUSE -GAMEPORT1 PHYS0

**Comment by captainys** [comment]
Thank you for testing in your environment!  Glad now Tsugaru supports mouse integration in all levels of Windows 3.1 released for Towns!
